meta_product_name: "Verifi"
meta_title: "Verifi - Take away account uncertainty, verifi."
meta_description: "Upload your photos to Verifi to check your photo's removal risk from Instagram. Recieve detailed information on your photo's risks and content."
meta_image: "ms-icon-310x310.png" # in `app/assets/images`
